name: Local CI/CD Simulation

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    env:
      HOME: D:\Work\ECatalog\OnlineECatalog\actions-runner

    steps:
    - name: Manually mark directory as safe
      run: |
        git config --global --add safe.directory "D:/Work/ECatalog/OnlineECatalog/actions-runner/_work/online-e-catalog/online-e-catalog"

    - name: Manual git init
      run: |
        cd $env:GITHUB_WORKSPACE
        git init
        git remote add origin https://github.com/Freezinggg/online-e-catalog.git
        git fetch origin main
        git checkout main
      shell: pwsh

    - name: Install .NET 9 manually
      run: |
        curl -L https://dot.net/v1/dotnet-install.ps1 -o install-dotnet.ps1
        pwsh ./install-dotnet.ps1 -Version 9.0.100 -InstallDir "$PWD/.dotnet"
      shell: pwsh

    - name: Add .NET to PATH
      run: |
        echo "$PWD/.dotnet" | Out-File -Append -Encoding ascii $env:GITHUB_PATH
        echo "DOTNET_ROOT=$PWD/.dotnet" | Out-File -Append -Encoding ascii $env:GITHUB_ENV
      shell: pwsh

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Publish
      run: dotnet publish -c Release -o ./out

    - name: Build Docker image
      run: docker build -t online-ecatalog .

    - name: Stop and remove previous container (PowerShell)
      run: |
        docker stop online-ecatalog 2>$null
        docker rm online-ecatalog 2>$null
      shell: pwsh

    - name: Run Docker container
      run: docker run -d -p 8080:80 --name online-ecatalog online-ecatalog
